sudo: false
os: linux
language: rust
cache: cargo
rust:
  - stable
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo build --all
  - cargo test --all
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ]