sudo: false
os: linux
language: rust
cache: cargo
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
rust:
  - stable
matrix:
  allow_failures:
    - rust: nightly
before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH    
script:
  - |
      travis-cargo build &&
      travis-cargo test -- --verbose &&
      travis-cargo bench -- --no-run 
after_success:
  - |
      wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
      tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build && cmake .. && make &&
      sudo make install && cd ../.. &&
      kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/test-data-generation-*
  - |    
      [ $TRAVIS_BRANCH = master ] &&
      [ $TRAVIS_PULL_REQUEST = false ] &&
      travis-cargo --only stable doc -- --no-deps &&
      travis-cargo --only stable doc-upload
env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=nightly