sudo: false
os: linux
language: rust
cache: cargo
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
rust:
  - nightly
  - stable
matrix:
  allow_failures:
    - rust: nightly
script:
  - |
      travis-cargo build &&
      travis-cargo test &&
      travis-cargo bench &&
      travis-cargo --only stable doc  
after_success:
  - travis-cargo --only stable doc-upload
  - travis-cargo coveralls --no-sudo --verify
env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=nightly