[package]
name = "test-data-generation"
version = "0.1.0"
authors = ["dsietz <davidsietz@yahoo.com>"]
repository = "https://github.com/dsietz/test-data-generation.git"
license = "Apache 2.0"
readme = "README.md"

[dependencies]
clap        = "2.26.2"
config      = "*"
lazy_static = "0.2"
log         = "0.3"
log4rs      = "0.7.0"
serde       = "1.0.14"
serde_yaml  = "0.7.1"
yaml-rust   = "0.3.5"
regex       = "0.2"
crossbeam   = "0.3.0"